/**
 * actions
 *
 * 异步action:
 *  1. REQUEST_GET_USER
 *  2. REQUEST_GET_USER_FAILURE || REQUEST_GET_USER_SUCCESS
 */

import keyMirror from 'keymirror';


module.exports = keyMirror({
  LOGIN_INPUT: null,
  LOGIN_REQUEST: null,
  LOGIN_REQUEST_SUCCESS: null,
  LOGIN_REQUEST_FAILURE: null,

  /**
   * 文章
   */

  REQUEST_GET_ARTICLES: null,
  REQUEST_GET_ARTICLES_SUCCESS: null,
  REQUEST_GET_ARTICLES_FAILURE: null,

  REQUEST_GET_ARTICLE: null,
  REQUEST_GET_ARTICLE_SUCCESS: null,
  REQUEST_GET_ARTICLE_FAILURE: null,

  REQUEST_DELETE_ARTICLE: null,
  REQUEST_DELETE_ARTICLE_SUCCESS: null,
  REQUEST_DELETE_ARTICLE_FAILURE: null,

  REQUEST_PATCH_ARTICLE: null,
  REQUEST_PATCH_ARTICLE_SUCCESS: null,
  REQUEST_PATCH_ARTICLE_FAILURE: null,

  EDIT_ARTICLE: null,

  /**
   * 用户
   */

  REQUEST_GET_USERS: null,
  REQUEST_GET_USERS_SUCCESS: null,
  REQUEST_GET_USERS_FAILURE: null,

  REQUEST_GET_USER: null,
  REQUEST_GET_USER_SUCCESS: null,
  REQUEST_GET_USER_FAILURE: null,

  REQUEST_DELETE_USER: null,
  REQUEST_DELETE_USER_SUCCESS: null,
  REQUEST_DELETE_USER_FAILURE: null,

  /**
   * 评论
   */

  REQUEST_GET_COMMENTS: null,
  REQUEST_GET_COMMENTS_SUCCESS: null,
  REQUEST_GET_COMMENTS_FAILURE: null,

  REQUEST_GET_COMMENT: null,
  REQUEST_GET_COMMENT_SUCCESS: null,
  REQUEST_GET_COMMENT_FAILURE: null,

  REQUEST_DELETE_COMMENT: null,
  REQUEST_DELETE_COMMENT_SUCCESS: null,
  REQUEST_DELETE_COMMENT_FAILURE: null
});
